spring:
  application:
    name: report

  cloud:
    azure:
      # 1. Blob Storage Passwordless Config
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT}
          container-name: ${STORAGE_CONTAINER_NAME}

      # 2. Event Hubs Passwordless Config
      eventhubs:
        namespace: ${AZURE_EVENTHUBS_NAMESPACE}
        event-hub-name: ${AZURE_EVENTHUBS_NAME}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: ${LOG_FILE_PATH:./logs/dataingest.log}

admin:
  user:
    password: ${ADMIN_USER_PASSWORD:report-admin-password}