name: CI

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-ci-workflow:
    uses: huyqlam-ops/shared-workflow/.github/workflows/ci.yml@main
    with:
      java_version: '25'
      retention_days: 7