name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build-release-deploy:
    uses: huyqlam-ops/shared-workflow/.github/workflows/cicd.yml@main
    with:
      image_name: 'report'
      container_name: 'report'
      java_version: '25'
      environment_name: 'dev'
    secrets: inherit